services:
  backend:
    command:
      - fastapi
      - dev
      - --port
      - "8000"
      - --host
      - "0.0.0.0"
      - src/app/main.py
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./backend/pyproject.toml
  frontend:
    build:
      target: builder
      args:
        VITE_API_URL: ${VITE_API_URL}
    command:
      - pnpm
      - run
      - dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .svelte-kit/
        - action: rebuild
          path: ./frontend/package.json
networks:
  traefik-public:
    external: false
